# -*- coding: utf-8 -*-
"""Colpali - Scratch version-HS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12h49QFBTNi2xMkSszqtZHMumC73K55Sq
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install transformers --upgrade
# !pip install colpali-engine --upgrade
# !pip install pdf2image
# !pip install openai
# !pip install qwen_vl_utils
# 
# !apt-get update
# !apt-get install poppler-utils
# !pip install poppler-utils
# 
# !pip install pymilvus --upgrade
#

# %%capture
# !apt-get update
# !apt-get install poppler-utils
# !pip install poppler-utils

# !pip install pymilvus --upgrade

# # !pip install milvus --upgrade
# !pip install pymilvus --upgrade
# !python3 -m pip install -U "milvus[client]" #pymilvus

from colpali_engine.models import ColQwen2, ColQwen2Processor
import torch
from torch.utils.data import DataLoader
from tqdm import tqdm
from PIL import Image

import torch
from PIL import Image

from colpali_engine.models import ColQwen2, ColQwen2Processor


model = ColQwen2.from_pretrained(
        "vidore/colqwen2-v0.1",
        torch_dtype=torch.bfloat16, # switch to float16 if gpu does not support it
        device_map="cuda:0",  # or "mps" if on Apple Silicon
    )
processor = ColQwen2Processor.from_pretrained("vidore/colqwen2-v0.1")
model = model.eval()

# upload a PDF - change this to put the document you cwant - doesn't need to be in English necessarily
!wget https://drive.google.com/file/d/1ZzLEssGKMBkWR90LM3MqxPeGAKhtaD6n/view?usp=sharing -O test.pdf

# upload a PDF - change this to put the document you cwant - doesn't need to be in English necessarily
!wget https://reseauactionclimat.org/wp-content/uploads/2018/04/powerpoint-final-kit.pdf -O test.pdf

# convert all PDF pages to images
from pdf2image import convert_from_path
import base64
from io import BytesIO


images = convert_from_path('./test.pdf')

base64_images = []
for i in range(len(images)):
    buffered = BytesIO()
    images[i].save(buffered, format="JPEG")
    base64_images.append(base64.b64encode(buffered.getvalue()).decode('utf-8'))

# Process the inputs by batches of 2 - modify it depending on your VRAM !
 # Run inference - docs
dataloader = DataLoader(
    dataset=images,
    batch_size=2,
    shuffle=False,
    collate_fn=lambda x: processor.process_images(x),
)

ds  = []
for batch_doc in tqdm(dataloader):
    with torch.no_grad():
        batch_doc = {k: v.to(model.device) for k, v in batch_doc.items()}
        embeddings_doc = model(**batch_doc)
    ds.extend(list(torch.unbind(embeddings_doc.to("cpu"))))

#Create DB and collection
#If you are running again pls give differen db name, need to handle if DB already exists exception
from pymilvus import MilvusClient
from pymilvus import FieldSchema, CollectionSchema, DataType

# Set up a Milvus client
client = MilvusClient(uri="milvus16.db")

DIMENSION= 128

fields=[
    FieldSchema(name='id', dtype=DataType.INT64, is_primary=True, auto_id=True), # Changed Int64 to INT64
    FieldSchema(name='embedding', dtype=DataType.FLOAT_VECTOR, dim=DIMENSION, metric_type="COSINE")
]

schema = CollectionSchema(fields=fields, enable_dynamic_field= True)

if client.has_collection(collection_name="invoices"):
    client.drop_collection(collection_name="invoices")
client.create_collection(
    collection_name="invoices",
    dimension=128,
    schema=schema,
    auto_id=True,
    enable_dynamic_field=True,
)

#Adding all embeddings along with their position index and file name
milvus_input = []
for i in range(len(ds)):
  for j in range(len(ds[i])):
      entry={}
      entry['embedding'] = ds[i][j]
      entry['file_name'] = 'file1'
      entry['i_index'] = i
      entry['j_index'] = j
      milvus_input.append(entry)
      print(client.insert(collection_name="invoices", data=entry))

# Query stored vectors based on file_name
filter_query = 'file_name == "file1"'  # Changed 'filter' to 'filter_query'

res = client.query(
    collection_name="invoices",
    filter=filter_query,
    output_fields=["file_name", "embedding","i_index","j_index"]
)

#from received vectos get max i and j indexes
i_index_max=0
j_index_max=0

for i in res:
  if i_index_max<i['i_index']:
    i_index_max=i['i_index']
  if j_index_max<i['j_index']:
    j_index_max=i['j_index']

# from below statement able to reconstruct the vector as before but along with metadata
# need to maintain exclude metadata attributes and have only vectos
str_res=[]
for i in range(i_index_max):
  str_res.append( sorted(list(filter(lambda x:x['i_index']==i,res)),key=lambda x:x['j_index']) )

# str_res=[item["score"] for item in sorted(data, key=lambda x: x["age"])]