# -*- coding: utf-8 -*-
"""GenerateEmbeddingsandQuery.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1omaNStjEn28arYMwIzZR_1Zyqv0Zfy_3

Install Neccessary Libraries
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install transformers --upgrade
# !pip install colpali-engine --upgrade
# !apt-get install poppler-utils
# !pip install pdf2image
# !pip install openai
# !pip install qwen_vl_utils

"""Import Libraries"""

from colpali_engine.models import ColQwen2, ColQwen2Processor
import torch #Framework to develop, test , deploy Machine learning Models
from torch.utils.data import DataLoader  # To load Large Data sets provided by Torch
from tqdm import tqdm  # display progress bars for loops and iterative processes,
from PIL import Image  # Pythom Imaging Library  used for opening, manipulating, and saving image files

"""## Colpali Embeddings

Model Loading
"""

import torch
from PIL import Image

from colpali_engine.models import ColQwen2, ColQwen2Processor


model = ColQwen2.from_pretrained(
        "vidore/colqwen2-v0.1",
        torch_dtype=torch.bfloat16, # switch to float16 if gpu does not support it
        device_map="cuda:0",  # or "mps" if on Apple Silicon
    )
processor = ColQwen2Processor.from_pretrained("vidore/colqwen2-v0.1")
model = model.eval()  #Set a model to evaluation mode

"""Document Conversion"""

# convert all PDF pages to images
from pdf2image import convert_from_path
import base64
from io import BytesIO

#images = convert_from_path('./test.pdf')
#images = convert_from_path('./PMI-472031.pdf')
images = convert_from_path('./realistic-invoice-1.pdf')
#print(len(images))  # No of pages in PDF
base64_images = []
for i in range(len(images)):
    buffered = BytesIO()
    images[i].save(buffered, format="JPEG")
    base64_images.append(base64.b64encode(buffered.getvalue()).decode('utf-8'))

"""Generate Embeddings"""

# Process the inputs by batches of 2 - modify it depending on your VRAM !
 # Run inference - docs
dataloader = DataLoader(
    dataset=images,
    batch_size=2,
    shuffle=False,
    collate_fn=lambda x: processor.process_images(x),
)

ds  = []
print(type(dataloader))

for batch_doc in tqdm(dataloader):
    #print(type(batch_doc))
    with torch.no_grad():  #disables gradient calculation.
        batch_doc = {k: v.to(model.device) for k, v in batch_doc.items()}
        embeddings_doc = model(**batch_doc)
    ds.extend(list(torch.unbind(embeddings_doc.to("cpu"))))
print(type(embeddings_doc))
for i in range(len(ds)):
    print(ds[i].shape)
image_mask = processor.get_image_mask(processor.process_images([images[3]]))
print(image_mask.shape)

"""Inference"""

def get_results(query: str):
    batch_queries = processor.process_queries([query]).to(model.device)

    # Forward pass
    with torch.no_grad():
        query_embeddings = model(**batch_queries)

    scores = processor.score_multi_vector(query_embeddings, ds)
    # get top-5 scores
    return scores[0].topk(2).indices.tolist()

# display and resize keepin aspect ratio
#idx = get_results("What animals are in danger with climate change ?")[0]
idx = get_results("Extract the role and rate for Cheryl Herzog")[0]
print(idx)
im = images[idx]
image_mask = processor.get_image_mask(processor.process_images([im]))
print(image_mask.shape)
def display_resize(im):
    shrink_factor = (im.size[0]/1024)
    display(im.resize((int(im.size[0]/shrink_factor), int(im.size[1]/shrink_factor))))

display_resize(im)

"""Interpretability"""

from colpali_engine.interpretability import (
    get_similarity_maps_from_embeddings,
    plot_all_similarity_maps,
    plot_similarity_map,
)


# Get the number of image patches
n_patches = processor.get_n_patches(
    image_size=im.size,
    patch_size=model.patch_size,
    spatial_merge_size=model.spatial_merge_size,
)


# Get the tensor mask to filter out the embeddings that are not related to the image
image_mask = processor.get_image_mask(processor.process_images([im]))
image_embeddings=ds[idx].unsqueeze(0).to("cuda")
print(ds[idx].shape)
print(image_mask.shape)
#print(idx)

batch_queries = processor.process_queries(["Extract all Pricebook , Net Price, Sum of Targt quantity, Sum of net value for PO 456789 in JSON format"]).to(model.device)
# Generate the similarity maps
batched_similarity_maps = get_similarity_maps_from_embeddings(
    image_embeddings=ds[idx].unsqueeze(0).to("cuda"),
    query_embeddings=model(**batch_queries),
    n_patches=n_patches,
    image_mask=image_mask,
)


query_content = processor.decode(batch_queries.input_ids[0]).replace(processor.tokenizer.pad_token, "")
query_content = query_content.replace(processor.query_augmentation_token, "").strip()
query_tokens = processor.tokenizer.tokenize(query_content)

# Get the similarity map for our (only) input image
similarity_maps = batched_similarity_maps[0]  # (query_length, n_patches_x, n_patches_y)


token_idx = 3 # for the third token

fig, ax = plot_similarity_map(
    image=im,
    similarity_map=similarity_maps[token_idx],
    figsize=(8, 8),
    show_colorbar=False,
)

max_sim_score = similarity_maps[token_idx, :, :].max().item()
ax.set_title(f"Token #{token_idx}: `{query_tokens[token_idx].replace('Ġ', '_')}`. MaxSim score: {max_sim_score:.2f}", fontsize=14)

del query_content, query_tokens, batch_queries, batched_similarity_maps, similarity_maps, image_mask, n_patches, im

"""Generating a response

Using Qwen2-VL
"""

from transformers import Qwen2VLForConditionalGeneration, AutoTokenizer, AutoProcessor
from qwen_vl_utils import process_vision_info
import torch


gen_model = Qwen2VLForConditionalGeneration.from_pretrained("vidore/colqwen2-base",torch_dtype=torch.bfloat16).cuda().eval()

max_pixels = 512*28*28    # decrease resolution to fit in RAM at the cost of performance (if you have more RAM, feel free to up 512 to much higher)
gen_processor = AutoProcessor.from_pretrained("Qwen/Qwen2-VL-2B-Instruct", max_pixels=max_pixels)

"""Prompt"""

PROMPT = """
Use the page to answer the query:
{query}
PDF pages:
"""

def get_answer_local(query: str):
    top_k = get_results(query)

    messages = [
        {
            "role": "user",
            "content": [
                {
                    "type": "image",
                    "image": images[top_k[0]],
                },
                {"type": "text", "text": PROMPT.format(query=query)},
            ],
        }
    ]

    text = processor.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )

    image_inputs, video_inputs = process_vision_info(messages)
    inputs = gen_processor(
        text=[text],
        images=image_inputs,
        videos=video_inputs,
        padding=True,
        return_tensors="pt",
    )
    inputs = inputs.to("cuda")

    generated_ids = gen_model.generate(**inputs, max_new_tokens=50)
    generated_ids_trimmed = [
        out_ids[len(in_ids) :] for in_ids, out_ids in zip(inputs.input_ids, generated_ids)
    ]
    output_text = gen_processor.batch_decode(
        generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=False
    )
    return output_text, top_k

# run retrieval
#answer, top_k = get_answer_local("We have a table for a Single  PO 456789. In this table there are 17 Pricebooks such as 234532-35.   For Each Pricebook there is Net Prices, Sum of Targt quantity, Sum of net value. I need all pricebook , net price, Sum of target Qunatity , Sum of Net Value in JSON format")
answer, top_k = get_answer_local("Extract the role and hourly rate for Cheryl Herzog")

#display_resize(images[top_k[0]])
print(answer)